/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 earth.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group {...props} dispose={null} scale={0.8}>
      <group position={[-0.4, -0.32, -0.48]} rotation={[0, -0.4, 0]} scale={2.38}>
        <mesh geometry={nodes.Icokugel001_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Icokugel001_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Icokugel001_3.geometry} material={materials['Material.007']} />
      </group>
      <group position={[1.51, 1.23, 0]} rotation={[-0.18, -0.31, -0.93]} scale={0.06}>
        <mesh geometry={nodes.Würfel_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.74, 0.85, 0.1]} rotation={[-0.16, -0.29, -1.2]} scale={[0.16, 0.1, 0.1]}>
        <mesh geometry={nodes.Würfel001_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel001_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-0.42, 1.76, 0.62]} rotation={[0.47, 0.81, -0.09]} scale={0.12}>
        <mesh geometry={nodes.Würfel002_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Würfel002_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Würfel002_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[1.28, 0.49, 0.93]} rotation={[0.79, -0.24, -0.84]} scale={[0.47, 0.09, 0.09]}>
        <mesh geometry={nodes.Würfel003_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Würfel003_2.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Würfel003_3.geometry} material={materials['Material.010']} />
      </group>
      <group position={[1.58, 1.1, 0.09]} rotation={[-0.14, -0.37, -1.03]} scale={0.06}>
        <mesh geometry={nodes.Würfel004_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel004_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.45, 1.24, 0.18]} rotation={[-0.14, -0.37, -1.03]} scale={0.06}>
        <mesh geometry={nodes.Würfel005_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel005_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.38, 1.36, 0.08]} rotation={[-0.18, -0.31, -0.93]} scale={0.06}>
        <mesh geometry={nodes.Würfel006_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel006_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.27, 1.47, 0]} rotation={[-0.12, -0.38, -0.75]} scale={0.06}>
        <mesh geometry={nodes.Würfel007_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel007_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.24, 1.47, 0.14]} rotation={[-0.12, -0.38, -0.75]} scale={0.06}>
        <mesh geometry={nodes.Würfel008_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel008_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.08, 1.64, -0.04]} rotation={[-0.12, -0.38, -0.75]} scale={0.06}>
        <mesh geometry={nodes.Würfel009_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel009_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.4, 1.39, -0.17]} rotation={[-0.18, -0.31, -0.93]} scale={0.06}>
        <mesh geometry={nodes.Würfel010_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel010_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.2, 1.58, -0.22]} rotation={[-0.12, -0.38, -0.75]} scale={0.06}>
        <mesh geometry={nodes.Würfel011_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel011_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.53, 1.23, -0.17]} rotation={[-0.18, -0.31, -0.93]} scale={0.06}>
        <mesh geometry={nodes.Würfel012_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel012_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.64, 1.06, -0.05]} rotation={[-0.14, -0.37, -1.03]} scale={0.06}>
        <mesh geometry={nodes.Würfel013_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel013_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.65, 1.1, -0.2]} rotation={[-0.18, -0.31, -0.93]} scale={0.06}>
        <mesh geometry={nodes.Würfel014_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel014_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.53, 1.28, -0.36]} rotation={[-0.18, -0.31, -0.93]} scale={0.06}>
        <mesh geometry={nodes.Würfel015_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel015_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.41, 1.43, -0.38]} rotation={[-0.18, -0.31, -0.93]} scale={0.06}>
        <mesh geometry={nodes.Würfel016_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel016_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[1.86, 0.67, -0.08]} rotation={[-0.16, -0.29, -1.2]} scale={[0.16, 0.1, 0.1]}>
        <mesh geometry={nodes.Würfel017_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel017_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[1.81, 0.87, -0.3]} rotation={[-0.26, -0.06, -1.12]} scale={[0.1, 0.06, 0.06]}>
        <mesh geometry={nodes.Würfel018_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel018_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.91, -0.86, 1.57]} rotation={[0.03, -1.03, -1.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel019_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel019_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.75, -1.01, 1.63]} rotation={[0.03, -1.03, -1.85]} scale={0.06}>
        <mesh geometry={nodes.Würfel020_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel020_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.92, -1.03, 1.52]} rotation={[0.03, -1.03, -1.85]} scale={0.06}>
        <mesh geometry={nodes.Würfel021_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel021_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.92, -0.68, 1.6]} rotation={[0.03, -1.03, -1.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel022_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel022_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.72, -0.86, 1.69]} rotation={[0.03, -1.03, -1.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel023_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel023_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.79, -1.21, 1.53]} rotation={[0.03, -1.03, -1.85]} scale={0.06}>
        <mesh geometry={nodes.Würfel024_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel024_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-0.09, -0.08, 2.03]} rotation={[-0.46, -1.49, -1.95]} scale={0.06}>
        <mesh geometry={nodes.Würfel025_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel025_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.07, -0.24, 2.03]} rotation={[-0.46, -1.49, -1.95]} scale={0.06}>
        <mesh geometry={nodes.Würfel026_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel026_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.15, -0.04, 1.99]} rotation={[-0.25, -1.34, -1.64]} scale={0.06}>
        <mesh geometry={nodes.Würfel027_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel027_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.2, -0.19, 2]} rotation={[-0.25, -1.34, -1.64]} scale={0.06}>
        <mesh geometry={nodes.Würfel028_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel028_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.64, -1.17, 1.64]} rotation={[-0.06, -1.02, -1.93]} scale={0.06}>
        <mesh geometry={nodes.Würfel029_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel029_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.24, -0.87, 1.15]} rotation={[-2.57, -0.84, 1.84]} scale={0.06}>
        <mesh geometry={nodes.Würfel030_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel030_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.28, -0.73, 1.12]} rotation={[-2.63, -0.67, 1.82]} scale={0.06}>
        <mesh geometry={nodes.Würfel031_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel031_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.33, -0.53, 1.08]} rotation={[-2.63, -0.67, 1.82]} scale={0.06}>
        <mesh geometry={nodes.Würfel032_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel032_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.47, -0.38, 0.94]} rotation={[-2.63, -0.67, 1.82]} scale={0.06}>
        <mesh geometry={nodes.Würfel033_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel033_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.35, -0.33, 1.08]} rotation={[-2.63, -0.67, 1.82]} scale={0.06}>
        <mesh geometry={nodes.Würfel034_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel034_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.38, -0.2, 1.02]} rotation={[-2.65, -0.61, 1.97]} scale={0.06}>
        <mesh geometry={nodes.Würfel035_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel035_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.3, 0.1, 1.08]} rotation={[-2.65, -0.61, 1.97]} scale={0.06}>
        <mesh geometry={nodes.Würfel036_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel036_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.34, -0.03, 1.06]} rotation={[-2.65, -0.61, 1.97]} scale={0.06}>
        <mesh geometry={nodes.Würfel037_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel037_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.28, -0.18, 1.15]} rotation={[-2.65, -0.61, 1.97]} scale={0.06}>
        <mesh geometry={nodes.Würfel038_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel038_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.22, -0.01, 1.19]} rotation={[-2.65, -0.61, 1.97]} scale={0.06}>
        <mesh geometry={nodes.Würfel039_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel039_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.56, -0.43, 1.73]} rotation={[-2.44, -0.92, 2.08]} scale={0.06}>
        <mesh geometry={nodes.Würfel040_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel040_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.75, -0.44, 1.61]} rotation={[-2.44, -0.92, 2.08]} scale={0.06}>
        <mesh geometry={nodes.Würfel041_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel041_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.67, -0.65, 1.64]} rotation={[-2.44, -0.92, 2.08]} scale={0.06}>
        <mesh geometry={nodes.Würfel042_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel042_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.46, -2.55, -0.93]} rotation={[-2.45, -0.93, 0.73]} scale={0.06}>
        <mesh geometry={nodes.Würfel043_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel043_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.34, -2.58, -0.98]} rotation={[-2.42, -0.92, 0.57]} scale={0.06}>
        <mesh geometry={nodes.Würfel044_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel044_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.23, -2.56, -1.2]} rotation={[-2.42, -0.92, 0.57]} scale={0.06}>
        <mesh geometry={nodes.Würfel045_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel045_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.08, -2.67, -0.98]} rotation={[-2.42, -0.92, 0.57]} scale={0.06}>
        <mesh geometry={nodes.Würfel046_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel046_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-0.99, -2.67, -1.12]} rotation={[-2.66, -0.98, 0.28]} scale={0.06}>
        <mesh geometry={nodes.Würfel047_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel047_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.21, -2.67, -0.72]} rotation={[-2.46, -0.92, 0.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel048_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel048_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.16, -1.61, -1.74]} rotation={[-1.95, -0.47, 0.96]} scale={0.06}>
        <mesh geometry={nodes.Würfel049_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel049_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.07, -1.72, -1.73]} rotation={[-2.02, -0.55, 0.83]} scale={0.06}>
        <mesh geometry={nodes.Würfel050_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel050_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.01, -1.82, -1.66]} rotation={[-2.02, -0.55, 0.83]} scale={0.06}>
        <mesh geometry={nodes.Würfel051_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel051_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.61, 1.54, -1.8]} rotation={[-0.71, -0.21, -0.37]} scale={0.06}>
        <mesh geometry={nodes.Würfel052_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel052_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.53, 1.5, -1.92]} rotation={[-0.71, -0.21, -0.37]} scale={0.06}>
        <mesh geometry={nodes.Würfel053_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel053_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.64, 1.49, -1.86]} rotation={[-0.71, -0.21, -0.37]} scale={0.06}>
        <mesh geometry={nodes.Würfel054_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel054_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.88, -1.33, -2.37]} rotation={[-1.85, 0.42, -0.54]} scale={0.06}>
        <mesh geometry={nodes.Würfel055_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel055_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.8, -1.5, -2.33]} rotation={[-1.85, 0.42, -0.54]} scale={0.06}>
        <mesh geometry={nodes.Würfel056_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel056_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.67, -1.42, -2.45]} rotation={[-1.85, 0.42, -0.54]} scale={0.06}>
        <mesh geometry={nodes.Würfel057_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel057_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.53, -1.61, -2.43]} rotation={[-2.03, 0.51, -0.48]} scale={0.06}>
        <mesh geometry={nodes.Würfel058_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel058_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.68, -1.65, -2.31]} rotation={[-2.03, 0.51, -0.48]} scale={0.06}>
        <mesh geometry={nodes.Würfel059_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel059_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.09, 1.59, -0.49]} rotation={[0.13, -0.06, 0.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel061_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel061_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.16, 1.52, -0.35]} rotation={[0.13, -0.06, 0.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel062_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel062_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.99, 1.67, -0.38]} rotation={[0.13, -0.06, 0.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel063_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel063_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.87, 1.75, -0.23]} rotation={[0.13, -0.06, 0.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel064_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel064_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.04, 1.6, -0.19]} rotation={[0.13, -0.06, 0.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel065_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel065_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2.18, 1.48, -0.11]} rotation={[0.13, -0.06, 0.71]} scale={0.06}>
        <mesh geometry={nodes.Würfel066_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel066_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-2, 1.53, 0]} rotation={[0.26, 0.05, 0.65]} scale={0.06}>
        <mesh geometry={nodes.Würfel067_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel067_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.87, 1.65, -0.02]} rotation={[0.26, 0.05, 0.65]} scale={0.06}>
        <mesh geometry={nodes.Würfel068_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel068_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.86, 1.55, 0.31]} rotation={[0.26, 0.05, 0.65]} scale={0.06}>
        <mesh geometry={nodes.Würfel069_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel069_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.12, 0.94, -2.54]} rotation={[-0.7, -0.57, 0.43]} scale={0.06}>
        <mesh geometry={nodes.Würfel070_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel070_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-0.99, 0.87, -2.62]} rotation={[-1.01, -0.67, 0.3]} scale={0.06}>
        <mesh geometry={nodes.Würfel071_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel071_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-0.88, 1.01, -2.56]} rotation={[-0.87, -0.64, 0.11]} scale={0.06}>
        <mesh geometry={nodes.Würfel072_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel072_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-1.01, 0.75, -2.66]} rotation={[-1.01, -0.67, 0.3]} scale={0.06}>
        <mesh geometry={nodes.Würfel073_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Würfel073_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.65, -0.64, 1.76]} rotation={[0.03, -1.18, -1.63]} scale={[0.16, 0.1, 0.1]}>
        <mesh geometry={nodes.Würfel075_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel075_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.44, -0.48, 1.86]} rotation={[0.03, -1.18, -1.63]} scale={[0.16, 0.1, 0.1]}>
        <mesh geometry={nodes.Würfel076_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel076_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.46, -0.91, 1.81]} rotation={[-0.04, -1.34, -1.79]} scale={[0.16, 0.1, 0.1]}>
        <mesh geometry={nodes.Würfel077_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel077_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.21, -1.82, 1.42]} rotation={[0.07, -1.27, -2.19]} scale={[0.12, 0.07, 0.07]}>
        <mesh geometry={nodes.Würfel078_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel078_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-0.22, -1.44, 1.73]} rotation={[-0.61, -1.41, -2.63]} scale={[0.12, 0.07, 0.07]}>
        <mesh geometry={nodes.Würfel079_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel079_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-1.28, 1.99, -0.13]} rotation={[2.26, -1.16, 2.03]} scale={[0.16, 0.1, 0.1]}>
        <mesh geometry={nodes.Würfel080_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel080_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-1.26, 1.94, 0.19]} rotation={[2.26, -1.16, 2.03]} scale={[0.1, 0.06, 0.06]}>
        <mesh geometry={nodes.Würfel081_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel081_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-0.73, 0.68, -2.81]} rotation={[-1.15, 0.39, 0.08]} scale={[0.16, 0.1, 0.1]}>
        <mesh geometry={nodes.Würfel082_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel082_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-0.91, 0.27, -2.86]} rotation={[-1.47, 0.34, 0.24]} scale={[0.16, 0.1, 0.1]}>
        <mesh geometry={nodes.Würfel083.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Würfel083_1.geometry} material={materials['Material.004']} />
      </group>
      <group position={[1.18, -1.99, -0.97]} rotation={[2.3, -0.87, -1.24]} scale={0.12}>
        <mesh geometry={nodes.Würfel084.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Würfel084_1.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Würfel084_2.geometry} material={materials['Material.013']} />
      </group>
      {/* <mesh geometry={nodes.Icokugel002.geometry} material={materials['Material.014']} position={[-0.01, 3.31, -0.75]} rotation={[0, 0.25, 0]} scale={0.37} />
      <mesh geometry={nodes.Icokugel001.geometry} material={materials['Material.014']} position={[1.15, -2.13, 2.47]} rotation={[0.63, -0.2, -1.19]} scale={0.37} />
      <mesh geometry={nodes.Icokugel003.geometry} material={materials['Material.014']} position={[-4.39, -1.27, 0.76]} rotation={[1.52, -0.48, 1.32]} scale={0.32} /> */}
      <mesh geometry={nodes.Icokugel004.geometry} material={materials['Material.014']} position={[2.99, 0.36, -1.29]} rotation={[-0.51, 0.12, -1.02]} scale={0.37} />
    </group>
  )
}

useGLTF.preload('/earth.gltf')
