import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React,{useRef, useEffect} from "react";
import Content from '../components/Content'
import Nav from '../components/Nav'
import route_pages from '../components/route_pages'
import Cursor from '../components/Cursor'



export default function Home() {
  
  

  
  return (
    <>
      <Head>
        <title>Ahmad Nasif</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container-fluid'>
      <ul className="circles animate__animated animate__fadeInUp animate__delay-0s">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li> 
      <li></li>
      </ul>
        <Nav />
        <Cursor />
        <div className='sec-scroll position-relative'>

        <section className='sec1 d-flex justify-content-center align-items-center color-purple'>
        <Content/>
        </section>

        
        </div>
        
        
      </div>
    </>
  )
}
